// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClientScheduleEditController from "./client_schedule_edit_controller"
application.register("client-schedule-edit", ClientScheduleEditController)

import DailyController from "./daily_controller"
application.register("daily", DailyController)

import DayoptWdaysController from "./dayopt_wdays_controller"
application.register("dayopt-wdays", DayoptWdaysController)

import DragScrollController from "./drag_scroll_controller"
application.register("drag-scroll", DragScrollController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HolidayMultiSelectController from "./holiday_multi_select_controller"
application.register("holiday-multi-select", HolidayMultiSelectController)

import LeftSidebarController from "./left_sidebar_controller"
application.register("left-sidebar", LeftSidebarController)

import NightPickerController from "./night_picker_controller"
application.register("night-picker", NightPickerController)

import ShiftEditController from "./shift_edit_controller"
application.register("shift-edit", ShiftEditController)

import SyncScrollController from "./sync_scroll_controller"
application.register("sync-scroll", SyncScrollController)

import UnsavedGuardController from "./unsaved_guard_controller"
application.register("unsaved-guard", UnsavedGuardController)
